# Create a postgis service using the postgis/postgis image.
services:
  db:
    image: postgis/postgis
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      # test: ["CMD-SHELL", "pg_isready -U postgres"]
      test: [
          "CMD-SHELL",
          'psql -U postgres -d postgres -c "SELECT ST_Buffer( ST_SetSRID(''POINT(0 0)''::GEOMETRY, 4326), 1) AS geom ;"',
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  # run-linter:
  #   build: .
  #   volumes:
  #     - .:/workspace/assignment01
  #   command: ["/workspace/assignment01/__entrypoints__/run_linter.sh", "."]

  run-tests:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASS: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_NAME: postgres
    volumes:
      - .:/assignment01
    command: [
      "/assignment01/__entrypoints__/run_tests.sh",
      "--",
      "--rootDir", "/assignment01",
      "__tests__/test_query01.js"]
