name: Lint SQL files

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    paths: [ '**/run_linter.sh', '**sql**' ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      # Hardcoding the image name here. Would rather use ${{ github.repository }},
      # but there may not be any uppercase characters in the name.
      image: ghcr.io/weitzman-musa-geocloud/assignment01:main

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Lint the SQL files
      run: __entrypoints__/run_linter.sh ${GITHUB_WORKSPACE}
