name: Test Query 03

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    paths: [ '**/run_tests.sh', '**03**' ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      # Hardcoding the image name here. Would rather use ${{ github.repository }},
      # but there may not be any uppercase characters in the name.
      image: ghcr.io/weitzman-musa-geocloud/assignment01:main
      env:
        POSTGRES_USER: postgres
        POSTGRES_PASS: postgres
        POSTGRES_HOST: db
        POSTGRES_PORT: 5432
        POSTGRES_NAME: postgres

    # Use the postgis image to start a postgres service
    #
    # See the following links for more information:
    # https://hub.docker.com/_/postgis
    # https://docs.github.com/en/actions/guides/about-service-containers
    # https://docs.github.com/en/actions/guides/creating-postgresql-service-containers
    services:
      db:
        image: postgis/postgis
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Run the test(s)
      run: |
        __entrypoints__/run_tests.sh -- \
          --rootDir ${GITHUB_WORKSPACE} \
          __tests__/test_query03.js
